# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import FieldMask_pb2 as FieldMask__pb2


class UserinfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserinfo = channel.unary_unary(
                '/fieldmask.UserinfoService/GetUserinfo',
                request_serializer=FieldMask__pb2.UserIdx.SerializeToString,
                response_deserializer=FieldMask__pb2.Userinfo.FromString,
                )


class UserinfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserinfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserinfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserinfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserinfo,
                    request_deserializer=FieldMask__pb2.UserIdx.FromString,
                    response_serializer=FieldMask__pb2.Userinfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fieldmask.UserinfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserinfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserinfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fieldmask.UserinfoService/GetUserinfo',
            FieldMask__pb2.UserIdx.SerializeToString,
            FieldMask__pb2.Userinfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
