# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FieldMask.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FieldMask.proto',
  package='fieldmask',
  syntax='proto3',
  serialized_options=b'\n\014example.grpcB\tUserProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x46ieldMask.proto\x12\tfieldmask\x1a google/protobuf/field_mask.proto\"x\n\x08Userinfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12#\n\x05image\x18\x03 \x01(\x0b\x32\x14.fieldmask.UserImage\x12-\n\tfieldmask\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.FieldMask\"\x19\n\x07UserIdx\x12\x0e\n\x06userId\x18\x01 \x01(\t\" \n\tUserImage\x12\x13\n\x0b\x64\x65\x63odedData\x18\x01 \x01(\t2I\n\x0fUserinfoService\x12\x36\n\x0bGetUserinfo\x12\x12.fieldmask.UserIdx\x1a\x13.fieldmask.UserinfoB\x1b\n\x0c\x65xample.grpcB\tUserProtoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR,])




_USERINFO = _descriptor.Descriptor(
  name='Userinfo',
  full_name='fieldmask.Userinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fieldmask.Userinfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='fieldmask.Userinfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='fieldmask.Userinfo.image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fieldmask', full_name='fieldmask.Userinfo.fieldmask', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=184,
)


_USERIDX = _descriptor.Descriptor(
  name='UserIdx',
  full_name='fieldmask.UserIdx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='fieldmask.UserIdx.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=211,
)


_USERIMAGE = _descriptor.Descriptor(
  name='UserImage',
  full_name='fieldmask.UserImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='decodedData', full_name='fieldmask.UserImage.decodedData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=245,
)

_USERINFO.fields_by_name['image'].message_type = _USERIMAGE
_USERINFO.fields_by_name['fieldmask'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
DESCRIPTOR.message_types_by_name['Userinfo'] = _USERINFO
DESCRIPTOR.message_types_by_name['UserIdx'] = _USERIDX
DESCRIPTOR.message_types_by_name['UserImage'] = _USERIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Userinfo = _reflection.GeneratedProtocolMessageType('Userinfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'FieldMask_pb2'
  # @@protoc_insertion_point(class_scope:fieldmask.Userinfo)
  })
_sym_db.RegisterMessage(Userinfo)

UserIdx = _reflection.GeneratedProtocolMessageType('UserIdx', (_message.Message,), {
  'DESCRIPTOR' : _USERIDX,
  '__module__' : 'FieldMask_pb2'
  # @@protoc_insertion_point(class_scope:fieldmask.UserIdx)
  })
_sym_db.RegisterMessage(UserIdx)

UserImage = _reflection.GeneratedProtocolMessageType('UserImage', (_message.Message,), {
  'DESCRIPTOR' : _USERIMAGE,
  '__module__' : 'FieldMask_pb2'
  # @@protoc_insertion_point(class_scope:fieldmask.UserImage)
  })
_sym_db.RegisterMessage(UserImage)


DESCRIPTOR._options = None

_USERINFOSERVICE = _descriptor.ServiceDescriptor(
  name='UserinfoService',
  full_name='fieldmask.UserinfoService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=247,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserinfo',
    full_name='fieldmask.UserinfoService.GetUserinfo',
    index=0,
    containing_service=None,
    input_type=_USERIDX,
    output_type=_USERINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERINFOSERVICE)

DESCRIPTOR.services_by_name['UserinfoService'] = _USERINFOSERVICE

# @@protoc_insertion_point(module_scope)
